seed: 0
batch_size: 64
encoding: integer
model: spiking_vggsnn
dataset: NMNIST
data_path: ../datasets/N-MNIST
workers: 16
attack: PGDTimeShiftL0
resume: ./checkpoints/VGGSNN_NMNIST.pth
output_dir: ./logs/PGDTimeShiftL0/integer/nmnist/vggsnn
