seed: 0
batch_size: 64
encoding: binary
model: simplenet_v2
dataset: NMNIST
data_path: ../datasets/N-MNIST
workers: 16
attack: PGDTimeShift
resume: ./checkpoints/SimpleNet_v2_NMNIST_binary.pth
output_dir: ./logs/PGDTimeShift/binary/nmnist/simplenet_v2
