seed: 0
batch_size: 64
encoding: binary
model: spiking_resnet18
dataset: CIFAR10DVS
data_path: ../datasets/CIFAR10DVS
workers: 16
attack: PGDTimeShift
resume: ./checkpoints/ResNet18_CIFAR10DVS_binary.pth
output_dir: ./logs/PGDTimeShift/binary/cifar10dvs/resnet18
