seed: 0
batch_size: 64
encoding: integer
model: simplenet_v2
dataset: NMNIST
data_path: ../datasets/N-MNIST
workers: 16
attack: PGDTimeShiftL0
resume: ./checkpoints/SimpleNet_v2_NMNIST.pth
output_dir: ./logs/PGDTimeShiftL0/integer/nmnist/simplenet_v2
