seed: 0
batch_size: 64
encoding: integer
model: spiking_resnet18
dataset: NMNIST
data_path: ../datasets/N-MNIST
workers: 16
attack: PGDTimeShiftL1
resume: ./checkpoints/ResNet18_NMNIST.pth
output_dir: ./logs/PGDTimeShiftL1/integer/nmnist/resnet18
