seed: 0
batch_size: 64
encoding: binary
model: spiking_vggsnn
dataset: DVSGesture
data_path: ../datasets/DVSGesture
workers: 16
attack: PGDTimeShift
resume: ./checkpoints/VGGSNN_adv1_eps8000_DVSGesture_binary.pth
output_dir: ./logs/PGDTimeShift/dvsgesture/vggsnn_adv1_eps8000
