seed: 0
batch_size: 8
encoding: binary
model: spiking_vggsnn_plif
dataset: DVSGesture
data_path: /home/yuyi/datasets/DVSGesture
workers: 16
attack: PGDTimeShiftL1
resume: /home/yuyi/PDSG-SDA/checkpoints/VGGSNN_PLIF_DVSGesture_binary.pth
output_dir: /home/yuyi/PDSG-SDA/logs/PGDTimeShiftL1/binary/dvsgesture/vggsnn_plif
