seed: 0
batch_size: 2
encoding: integer
model: spikingresformer_s
dataset: DVSGesture
data_path: ../datasets/DVSGesture
workers: 16
attack: PGDTimeShiftL1
resume: /home/yuyi/SpikingResformer-main/outputs/dvsg_integer/checkpoint_max_acc1.pth
output_dir: ./logs/PGDTimeShiftL1/integer/dvsgesture/spikingresformer_s
