seed: 0
batch_size: 64
encoding: integer
model: spiking_vggsnn
dataset: DVSGesture
data_path: ../datasets/DVSGesture
workers: 16
attack: PGDTimeShiftL0
resume: ./checkpoints/VGGSNN_adv_eps1_DVSGesture.pth
output_dir: ./logs/PGDTimeShiftL0/integer/dvsgesture/vggsnn_adv_eps1
