seed: 0
batch_size: 2
encoding: binary
model: spikingresformer_dvsg
dataset: DVSGesture
data_path: ../datasets/DVSGesture
workers: 16
attack: PGDTimeShiftL1
resume: ./checkpoints/spikingresformer_DVSGesture_binary.pth
output_dir: ./logs/PGDTimeShiftL1/binary/dvsgesture/spikingresformer
