seed: 0
batch_size: 64
encoding: binary
model: spiking_vggsnn
dataset: NMNIST
data_path: ../datasets/N-MNIST
workers: 16
attack: PGDTimeShiftL0
resume: ./checkpoints/VGGSNN_NMNIST_binary.pth
output_dir: ./logs/PGDTimeShiftL0/binary/nmnist/vggsnn
