seed: 0
batch_size: 8
encoding: integer
model: spiking_vggsnn
dataset: DVSGesture
data_path: /home/yuyi/datasets/DVSGesture
workers: 16
attack: PGDTimeShiftL0
resume: /home/yuyi/PDSG-SDA/checkpoints/VGGSNN_DVSGesture.pth
output_dir: /home/yuyi/PDSG-SDA/logs/PGDTimeShiftL0/integer/dvsgesture/vggsnn
