seed: 0
batch_size: 2
encoding: binary
model: spikingresformer_s
dataset: CIFAR10DVS
data_path: ../datasets/CIFAR10DVS
workers: 16
attack: PGDTimeShiftL1
resume: /home/yuyi/SpikingResformer-main/outputs/cifar10dvs_binary/checkpoint_max_acc1.pth
output_dir: ./logs/PGDTimeShiftL1/binary/cifar10dvs/spikingresformer_s
