seed: 0
batch_size: 2
T: 10
encoding: integer
model: spikingresformer_cifar
dataset: CIFAR10DVS
data_path: ../datasets/CIFAR10DVS
workers: 4
attack: SpikeFool
attack_eps: 0
resume: ./checkpoints/spikingresformer_CIFAR10DVS.pth
output_dir: ./rebuttal/logs/SpikeFool/cifar10dvs/spikingresformer/integer

