# seed: 0
# batch_size: 8
# encoding: integer
# model: spiking_vggsnn
# dataset: CIFAR10DVS
# data_path: /home/yuyi/datasets/CIFAR10DVS
# workers: 16
# attack: Clean
# resume: /home/yuyi/PDSG-SDA/checkpoints/VGGSNN_CIFAR10DVS.pth
# output_dir: /home/yuyi/PDSG-SDA/logs/Clean/integer/cifar10dvs/vggsnn


seed: 0
batch_size: 64
T: 10
encoding: integer
model: spiking_vggsnn
dataset: CIFAR10DVS
data_path: ../datasets/CIFAR10DVS
workers: 4
attack: SDA
attack_eps: 0
resume: ./checkpoints/VGGSNN_CIFAR10DVS.pth
output_dir: ./rebuttal/logs/SDA/cifar10dvs/vggsnn/integer